### ISSUE TITLE
Feature request: native Windows support

### ISSUE THREAD

**Issue by aitap** [j256/dmalloc#23]
I have a Windows-only project that dmalloc could really help with. Currently, it seems that the only way to use dmalloc on Windows is to build it with Cygwin, since the only virtual memory APIs that dmalloc currently speaks are `sbrk` and `mmap`, and Windows has neither.

If you are interested in this, I could prepare a pull request modifying `heap.c` to use `VirtualAlloc` / `VirtualFree` in addition to `mmap` / `munmap`, bringing me closer to my goal of cross-compiling dmalloc for Windows using something like `./configure --build=i686-linux-gnu --host=i686-w64-mingw32`. While lack of `mmap` could be worked around using `INTERNAL_MEMORY_SPACE`, it's not a good solution.

**Comment by aitap** [comment]
This is probably harder than it looks like:
 * Functions in `append.c` pass `va_list`s to other functions, expecting state modifications done by `va_arg()` in the callee to persist in the caller. Apparently this is not the case for mingw (where `va_list` could be just a `char *`), so `loc_snprintf(setup, sizeof(setup), "debug=%#x,start=%s:%d", 0x400, loc_file, loc_line);` crashes while trying to dereference `0x400` instead of `loc_file`.
 * For logging purposes, addresses are cast to `long`. Unfortunately, `long` is 32-bit in 64-bit Windows. Thankfully, there is only one `long` &rarr; `DMALLOC_PNT` cast, in [env.c](j256/dmalloc/blob/6c59d7b28f0a10335442e4d61d4b00b10abd4596/env.c#L115). Fixing this in a portable manner would be "fun".

**Comment by j256** [comment]
Thanks much @aitap .  I don't quite understand your point.  Am I doing something wrong with the `va_list` stuff or is there some incompatibility in it under windows?

**Comment by j256** [comment]
OH!  I see it.  I bet that's a bug.  Let me see if I can reproduce it in testing.

**Comment by j256** [comment]
I don't get the 2nd bullet?  Is there more to do?  should that be a 2nd issue maybe?

**Comment by j256** [comment]
Fixed the va_args usage with https://github.com/j256/dmalloc/pull/27

**Comment by j256** [comment]
I get the second bullet now.  Hrm.   So when we are printing the value as "%#lx" and I extract it as a long, that won't work.  Maybe I should be more religious about %p and extract it as a `char *`?

**Comment by j256** [comment]
Is there a `long long` or some other 64 bit numerical type?

**Comment by j256** [comment]
I just pushed up this pull request.  Does it fix anything?  https://github.com/j256/dmalloc/pull/28

**Comment by aitap** [comment]
Thanks a lot for your help!

**Comment by j256** [comment]
Sure thing.  Appreciate your feedback.
