### ISSUE TITLE
installdocs issues

### ISSUE THREAD

**Issue by matthewluckie** [j256/dmalloc#51]
make installdocs returns:

make[2]: don't know how to make ./dmalloc.info. Stop

I think the issue is that there's a rule in Makefile.in for dmalloc.info via INFOFILE but not one for ./dmalloc.info.

In Makefile.in:

```
-installdocs : $(srcdir)/$(HTMLFILE) $(srcdir)/$(INFOFILE)
+installdocs : $(srcdir)/$(HTMLFILE) $(INFOFILE)

 $(INFOFILE) : $(srcdir)/dmalloc.texi
 	rm -f $@ $@.t
-	makeinfo -o $@.t --fill-column=100 --no-split $<
+	makeinfo -o $@.t --fill-column=100 --no-split $(srcdir)/dmalloc.texi
```

fixes it for me.

BTW, DOCFILES specifies non-existent documentation files, and is only used in an echo statement.

**Comment by j256** [comment]
This was super tricky but I think I finally fixed.  Had a problem with it and the html file.  Sorry @matthewluckie .
